Added enumeration of other persistence mechanisms to AutorunsToWinEventLog.ps1
palantir/windows-event-forwarding pull request #23
Opened 2018-07-17 15:54 UTC by vector-sec

I added enumeration of BITS jobs, Desktop shortcuts, and Browser extensions to the script, using event ID 2, 3, and 4 respectively for each new class of data.

These modifications were made because SysInternals Autoruns does not presently support enumeration these persistence mechanisms.

ATT&CK References
https://attack.mitre.org/wiki/Technique/T1197
https://attack.mitre.org/wiki/Technique/T1176
https://attack.mitre.org/wiki/Technique/T1023

2018-07-17 15:54 UTC, palantirtech commented
Thanks for your interest in [palantir/windows-event-forwarding](https://github.com/palantir/windows-event-forwarding), @vector-sec! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2018-07-26 17:22 UTC, clong commented
Hey @vector-sec, thanks for the contribution! I've got a bit on my plate at the moment, but should be finished with a review of this in a week or so.

2018-11-29 03:26 UTC, clong requested changes
Sorry this review took so long! Just a few small issues to iron out here.

2018-12-04 01:01 UTC, clong commented on AutorunsToWinEventLog/AutorunsToWinEventLog.ps1
> +# 2 - BITS jobs
Numbering will need to be updated as this PR reserved #2: https://github.com/palantir/windows-event-forwarding/pull/30

2019-08-23 17:57 UTC, clong commented
Closing due to inactivity.

2019-08-23 17:57 UTC, closed without merging